// <auto-generated />
using System;
using ETicaretSitesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ETicaretSitesi.Migrations
{
    [DbContext(typeof(ETicaretDbContext))]
    [Migration("20250527111257_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ETicaretSitesi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("AdminMi")
                        .HasColumnType("bit");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Admin",
                            AdminMi = true,
                            Adres = "Admin Adresi",
                            AktifMi = true,
                            Email = "admin@example.com",
                            KayitTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(3135),
                            KullaniciAdi = "",
                            Rol = "Kullanici",
                            Sifre = "Admin123!",
                            Soyad = "User",
                            Telefon = "5551234567"
                        });
                });

            modelBuilder.Entity("ETicaretSitesi.Models.SepetUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UrunId");

                    b.ToTable("SepetUrunleri");
                });

            modelBuilder.Entity("ETicaretSitesi.Models.Siparis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("OdemeDurumu")
                        .HasColumnType("int");

                    b.Property<int>("SiparisDurumu")
                        .HasColumnType("int");

                    b.Property<string>("SiparisNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("ETicaretSitesi.Models.SiparisUrun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Adet")
                        .HasColumnType("int");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SiparisId")
                        .HasColumnType("int");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiparisId");

                    b.HasIndex("UrunId");

                    b.ToTable("SiparisUrunleri");
                });

            modelBuilder.Entity("ETicaretSitesi.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("GorselUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StokMiktari")
                        .HasColumnType("int");

                    b.Property<int>("UrunTipi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Urunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Apple'ın en güçlü M2 çipi ile donatılmış MacBook Pro, 13.3 inç Retina ekranı, 8GB birleşik bellek ve 256GB SSD depolama alanı ile profesyonel kullanım için mükemmel performans sunar. Touch Bar ve Touch ID özelliği ile güvenlik ve kullanım kolaylığı sağlar. 10 saate kadar pil ömrü ile mobil çalışma için ideal.",
                            Ad = "MacBook Pro M2",
                            AktifMi = true,
                            Fiyat = 42999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2821),
                            ResimUrl = "/images/laptop1.jpg",
                            StokMiktari = 10,
                            UrunTipi = 1
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Intel Core i7 işlemci ile güçlendirilmiş Dell XPS 13, 13.4 inç 4K Ultra HD InfinityEdge ekranı ile kristal netliğinde görüntü sunar. 16GB LPDDR4x RAM ve 512GB PCIe SSD ile hızlı performans. Premium alüminyum kasası ve karbon fiber iç yüzeyi ile şık tasarım. Windows 11 Pro ile gelir.",
                            Ad = "Dell XPS 13",
                            AktifMi = true,
                            Fiyat = 34999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2854),
                            ResimUrl = "/images/laptop2.jpg",
                            StokMiktari = 8,
                            UrunTipi = 1
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Intel Core i5, 14 inç FHD ekran, 16GB RAM, 512GB SSD",
                            Ad = "Lenovo ThinkPad X1",
                            AktifMi = true,
                            Fiyat = 27999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2858),
                            ResimUrl = "/images/laptop3.jpg",
                            StokMiktari = 12,
                            UrunTipi = 1
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Intel Core i7, 13.5 inç OLED ekran, 16GB RAM, 1TB SSD",
                            Ad = "HP Spectre x360",
                            AktifMi = true,
                            Fiyat = 31999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2859),
                            ResimUrl = "/images/laptop4.jpg",
                            StokMiktari = 6,
                            UrunTipi = 1
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "AMD Ryzen 9, 15.6 inç 165Hz ekran, 32GB RAM, 1TB SSD",
                            Ad = "Asus ROG Zephyrus",
                            AktifMi = true,
                            Fiyat = 45999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2861),
                            ResimUrl = "/images/laptop5.jpg",
                            StokMiktari = 4,
                            UrunTipi = 1
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "A17 Pro çip, 6.1 inç Super Retina XDR ekran, 128GB",
                            Ad = "iPhone 15 Pro",
                            AktifMi = true,
                            Fiyat = 49999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2863),
                            ResimUrl = "/images/telefon1.jpg",
                            StokMiktari = 15,
                            UrunTipi = 0
                        },
                        new
                        {
                            Id = 7,
                            Aciklama = "Samsung'un en gelişmiş akıllı telefonu Galaxy S24 Ultra, Snapdragon 8 Gen 3 işlemci ile üstün performans sunar. 6.8 inç Dynamic AMOLED 2X ekranı, 120Hz yenileme hızı ve S Pen desteği ile profesyonel kullanım için ideal. 200MP ana kamera, 12GB RAM ve 256GB depolama alanı. 5000mAh pil ile uzun kullanım süresi.",
                            Ad = "Samsung Galaxy S24 Ultra",
                            AktifMi = true,
                            Fiyat = 44999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2864),
                            ResimUrl = "/images/telefon2.jpg",
                            StokMiktari = 12,
                            UrunTipi = 0
                        },
                        new
                        {
                            Id = 8,
                            Aciklama = "Google Tensor G3, 6.7 inç LTPO OLED ekran, 256GB",
                            Ad = "Google Pixel 8 Pro",
                            AktifMi = true,
                            Fiyat = 39999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2866),
                            ResimUrl = "/images/telefon3.jpg",
                            StokMiktari = 10,
                            UrunTipi = 0
                        },
                        new
                        {
                            Id = 9,
                            Aciklama = "Snapdragon 8 Gen 3, 6.73 inç AMOLED ekran, 512GB",
                            Ad = "Xiaomi 14 Pro",
                            AktifMi = true,
                            Fiyat = 34999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2867),
                            ResimUrl = "/images/telefon4.jpg",
                            StokMiktari = 8,
                            UrunTipi = 0
                        },
                        new
                        {
                            Id = 10,
                            Aciklama = "Snapdragon 8 Gen 3, 6.82 inç AMOLED ekran, 256GB",
                            Ad = "OnePlus 12",
                            AktifMi = true,
                            Fiyat = 29999.99m,
                            GorselUrl = "",
                            OlusturmaTarihi = new DateTime(2025, 5, 27, 14, 12, 56, 529, DateTimeKind.Local).AddTicks(2873),
                            ResimUrl = "/images/telefon5.jpg",
                            StokMiktari = 14,
                            UrunTipi = 0
                        });
                });

            modelBuilder.Entity("ETicaretSitesi.Models.SepetUrun", b =>
                {
                    b.HasOne("ETicaretSitesi.Models.Kullanici", "Kullanici")
                        .WithMany("SepetUrunleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETicaretSitesi.Models.Urun", "Urun")
                        .WithMany("SepetUrunleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("ETicaretSitesi.Models.Siparis", b =>
                {
                    b.HasOne("ETicaretSitesi.Models.Kullanici", "Kullanici")
                        .WithMany("Siparisler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("ETicaretSitesi.Models.SiparisUrun", b =>
                {
                    b.HasOne("ETicaretSitesi.Models.Siparis", "Siparis")
                        .WithMany("SiparisUrunleri")
                        .HasForeignKey("SiparisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ETicaretSitesi.Models.Urun", "Urun")
                        .WithMany("SiparisUrunleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siparis");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("ETicaretSitesi.Models.Kullanici", b =>
                {
                    b.Navigation("SepetUrunleri");

                    b.Navigation("Siparisler");
                });

            modelBuilder.Entity("ETicaretSitesi.Models.Siparis", b =>
                {
                    b.Navigation("SiparisUrunleri");
                });

            modelBuilder.Entity("ETicaretSitesi.Models.Urun", b =>
                {
                    b.Navigation("SepetUrunleri");

                    b.Navigation("SiparisUrunleri");
                });
#pragma warning restore 612, 618
        }
    }
}
